# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter oneplus7pro oneplus7 oneplus7tpro oneplus7t,$(TARGET_DEVICE)),)

endif
