# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter oneplus8 oneplus8pro oneplus8t oneplus9r,$(TARGET_DEVICE)),)

endif
